import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [text, setText] = useState<string>("");
  const [shortened, setShortened] = useState<string>("");
  const [streamEnded, setStreamEnded] = useState(false);

  const handleSummaryCall = async () => {
    const inputData = {
      model: "llama2",
      prompt: text,
    };

    let concatenatedResponse = "";

    const response = await fetch("http://localhost:11434/api/generate", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(inputData),
    });
    const reader = response.body.getReader();

    while (!streamEnded) {
      const { value, done } = await reader.read();
      if (done) {
        setStreamEnded(true);
        break;
      }

      try {
        const jsonData = JSON.parse(new TextDecoder().decode(value));
        if (jsonData.done) {
          setStreamEnded(true);
        } else {
          console.log(jsonData.response);
          concatenatedResponse += jsonData.response;
          setShortened(concatenatedResponse);
        }
      } catch (error) {
        console.error("Error parsing JSON:", error);
      }
    }
    setStreamEnded(false);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black">
        <div className="container flex min-w-full max-w-screen-lg flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Make it short
          </h1>
          <div className="flex min-w-full max-w-none flex-col items-center justify-center gap-4">
            <textarea
              className="w-1/2 rounded-md px-4 py-2 text-xl font-semibold text-black focus:outline-none"
              placeholder="Text to summarize"
              value={text}
              onChange={(e) => setText(e.target.value)}
              onKeyDown={async (e) => {
                if (e.key === "Enter") {
                  await handleSummaryCall();
                }
              }}
            />
            <button
              className="rounded-md bg-[#2acf2d] px-4 py-2 text-lg font-bold text-white focus:outline-none"
              type="button"
              onClick={handleSummaryCall}
            >
              Shorten it!
            </button>
            <div className="flex max-w-screen-sm flex-col">
              <h1 className="text-2xl font-extrabold tracking-tight text-white">
                {shortened}
              </h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
